### ISSUE TITLE
Why so opinionated?

### ISSUE THREAD

**Issue by stereokai** [Yoobic/install-mac#18]
This is a grand idea. However, what's the point with installing some software that is very user-specific? Consider the following:

* Skype
* Dropbox
* Sublime Text 3
* VirtualBox
* Slack
* LimeChat

Let's say I am not a freelancer nor do I have any remote-located friends to keep in touch with. Why would I need Skype? Or, if I use WebStorm, Brackets, Atom, or (god forbid) Emacs why would I have to sacrifice hard disk cycles for an entire ecosystem with it's dependencies all of I will not touch (ST3)?

And if I am considered lucky enough to not have to deal with testing anything on multiple platforms, I don't see any good reason an installation of VirtualBox should be forced on me. The same applies for all the rest in that list.

Moving on.

* gulp - providing the installation of the gulp-cli is cool – you want to avoid npm from having to download, cache, and compile it... which would happen *anyway* on the first project I would install that *requires it*... This point applies to **all the libraries listed below**. But that's fine. However, there's another issue to consider: most open source projects rely on gruntjs for task running – so, to illustrate, when want to contribute to some popular repository on my brand new laptop and `npm install` it, npm has to download, cache, and compile grunt-cli — suggesting an overlook considering what you are trying to accomplish here.

* browser-sync
* jshint
* eslint
* jscs
* browserify
* watchify
* nodemon
* node-inspector
* cordova
* phonegap
* ionic

To continue with what I said earlier, these are so specific to every project, and developer. I really don't see any point why an Angular dev for example, should have node.js  debugging tools, or cordova, phonegap and ionic **preinstalled** on their machine.

This package seems very personally-tailored and addressing this could contribute to this project gaining mainstream support. Thanks for reading.

**Comment by thaiat** [comment]
hi @stereokai, thanks for your feedback 

you are correct, i m very opinionated and my use case is to install a laptop for a new member of my team as fast and as easy as possible. That explains the list of things that get installed.

So one possible use of that project would be instead of use it 'as-is', to adapt it to your specific needs.

That being said, the tools related to node dev are very angular focused. Installing `gulp` as a global is not redondant with the local `gulp` installation that goes on when you `npm install` a repo that uses `gulp`. You need both.

If you are yourself developing with angular, i recommend that you give a shot to node-inspector. It is very helpfull when you want to debug, let's say a gulp/grunt task, or even karma, or any other node process that you may use when building your application. Not everything is client side event if your app is client only (lint, minification, sass, etc...)

That being said, i could make the installer a bit less opinionated with a dialog box/multiple choices asking the user to confirm its choices. What do you think of that ?

**Comment by stereokai** [comment]
"Installing gulp as a global is not redondant with the local gulp installation that goes on when you npm install a repo that uses gulp." - that is of course correct, and my bad for mixing between the two.

"That being said, i could make the installer a bit less opinionated with a dialog box/multiple choices asking the user to confirm its choices. What do you think of that ?"

I think that that sounds exactly like what I would do :)

**Comment by thaiat** [comment]
do you wanna contribute and make a PR ?

**Comment by thaiat** [comment]
implemented let me know what you think
